// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// UpdateIterR
Rcpp::List UpdateIterR(IntegerMatrix mat_sp, IntegerMatrix mat_suc, NumericVector c_e, NumericVector c_l, NumericVector c_s, NumericVector ss, double prob_distur, double prob_suc, double K, int n);
RcppExport SEXP TheoTradeOff_UpdateIterR(SEXP mat_spSEXP, SEXP mat_sucSEXP, SEXP c_eSEXP, SEXP c_lSEXP, SEXP c_sSEXP, SEXP ssSEXP, SEXP prob_disturSEXP, SEXP prob_sucSEXP, SEXP KSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type mat_sp(mat_spSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type mat_suc(mat_sucSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type c_e(c_eSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type c_l(c_lSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type c_s(c_sSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ss(ssSEXP);
    Rcpp::traits::input_parameter< double >::type prob_distur(prob_disturSEXP);
    Rcpp::traits::input_parameter< double >::type prob_suc(prob_sucSEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    __result = Rcpp::wrap(UpdateIterR(mat_sp, mat_suc, c_e, c_l, c_s, ss, prob_distur, prob_suc, K, n));
    return __result;
END_RCPP
}
