# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Run cellular automaton based on initila condition and species parameters n times
#' 
#' @param mat_sp landscape matrix of cells with species code if occupied.
#' @param mat_succ landscape matrix of cells successional status.
#' @param c_e vector of species early successional competitive ability.
#' @param c_l vector of species late successional competitive ability.
#' @param c_s vector of species abiotic stress tolerance.
#' @param ss vector of abiotic stress.
#' @param prob_distur probablity of cell disturbance (mortality).
#' @param prob_suc probablity of cell succession.
#' @param K strength of the competitive asymmetry parameter.
#' @param n number of repetition of landscape updating.
#' @export
UpdateIterR <- function(mat_sp, mat_suc, c_e, c_l, c_s, ss, prob_distur, prob_suc, K, n) {
    .Call('TheoTradeOff_UpdateIterR', PACKAGE = 'TheoTradeOff', mat_sp, mat_suc, c_e, c_l, c_s, ss, prob_distur, prob_suc, K, n)
}

